### ISSUE TITLE
[BUG] Android app crashes after entering password when host authentication is set to 'None'

### ISSUE THREAD

**Issue by seh-len** [Termix-SSH/Support#386]
### Title

Android app crashes after entering password when host authentication is set to 'None'

### Platform

App - Android

### Server Installation Method

Docker

### Version

1.9.0

### Troubleshooting

- [x] I have examined logs and tried to find the issue
- [x] I have reviewed opened and closed issues
- [x] I have tried restarting the application
- [x] I have read Known Issues (https://github.com/Termix-SSH/Support/issues/296)

### The Problem

When creating/configuring a host and selecting authentication: None (so the server prompts for a password), the Android app crashes immediately after entering the password.

termix version on android is 1.2.0

### How to Reproduce

1. Open Termix on Android.
2. Add or edit a Host.
3. Set Authentication to None (intended behavior: server asks for password).
4. Connect to the Host.
5. When prompted, enter the password.
6. Confirm / submit the password prompt.

### Additional Context

E AndroidRuntime: FATAL EXCEPTION: mqt_v_native
E AndroidRuntime: Process: com.karmaa.termix, PID: 6127
E AndroidRuntime: com.facebook.react.common.JavascriptException: ReferenceError: Property 'setIsConnecting' doesn't exist, stack:
E AndroidRuntime: anonymous@1:2734163
E AndroidRuntime: t6@1:2855227
E AndroidRuntime: _performTransitionSideEffects@1:561967
E AndroidRuntime: _receiveSignal@1:561595
E AndroidRuntime: onResponderRelease@1:560795
E AndroidRuntime: executeDispatch@1:277742
E AndroidRuntime: executeDispatchesAndReleaseTopLevel@1:283297
E AndroidRuntime: forEachAccumulated@1:279258
E AndroidRuntime: anonymous@1:283737
E AndroidRuntime: batchedUpdatesImpl@1:352838
E AndroidRuntime: batchedUpdates$1@1:283221
E AndroidRuntime: dispatchEvent@1:283502
E AndroidRuntime: 
E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.kt:52)
E AndroidRuntime: 	at com.facebook.jni.NativeRunnable.run(Native Method)
E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:995)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.kt:21)
E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:273)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:363)
E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion.startNewBackgroundThread$lambda$1(MessageQueueThreadImpl.kt:175)
E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion.$r8$lambda$ldnZnqelhYFctGaUKkOKYj5rxo4(Unknown Source:0)
E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1119)

**Comment by agreenbhm** [comment]
I'm experiencing this as well; just confirming it's not only OP.

**Comment by ZacharyZcR** [comment]
Maintainer note - 2026-05-31

Audited current shared terminal implementation against this crash report. The reported stack mentions setIsConnecting being missing, but the current Terminal component defines and uses setIsConnecting, and authType=none has a credential-prompt/reconnect path in the shared terminal backend/frontend code.

This may have been fixed by later terminal refactors, but I cannot verify the old Android React Native bundle from this repository. Keeping this open for now and marking it as needing a current-version Android retest; if it no longer reproduces, this can be closed.

**Comment by seh-len** [comment]
The problem persists in the current android version of termix. Although the app no longer crashes, sessions attempting to connect with “none” authentication are terminated immediately before the password is entered, and it is not possible to connect to such hosts via the android app.

**Comment by ZacharyZcR** [comment]
2026-05-31 update: Mobile-side fix is in Termix-SSH/Mobile#23. The PR keeps authType=none terminal sessions waiting for credentials instead of treating authentication-related prompts/errors as immediate terminal failures, and it reconnects with submitted credentials if the original Android WebSocket has already closed.

**Comment by ZacharyZcR** [comment]
Hey, has this issue been fixed in version 2.3.2?

**Comment by seh-len** [comment]
Not for me, all I see in the Android client is a “disconnected” message.

```
termix  | [9:55:15 AM] [INFO] [🖥️] Terminal WebSocket connection established [op:terminal_ws_connect,user:WMkR7k4lzxxxxx,session:-gBYbhsRUiiRPvoEv9oE-]
termix  | [9:55:15 AM] [INFO] [🖥️] Resolving SSH host configuration [op:terminal_host_resolve,user:WMkR7k4lzxxxxx,host:2,session:-gBYbhsRUiiRPvoEv9oE-]
termix  | [9:55:15 AM] [INFO] [🖥️] Initiating SSH connection [op:terminal_ssh_connect_attempt,user:WMkR7k4lzxxxxx,host:2,session:-gBYbhsRUiiRPvoEv9oE-]
termix  | [9:55:15 AM] [INFO] [🖥️] Host key verified successfully [op:host_key_verified,user:WMkR7k4lzxxxxx,host:2]
termix  | [9:55:15 AM] [ERROR] [🖥️] SSH connection error [op:ssh_connect,host:2]
termix  | Error: All configured authentication methods failed
termix  |     at doNextAuth (/app/node_modules/ssh2/lib/client.js:863:21)
termix  |     at tryNextAuth (/app/node_modules/ssh2/lib/client.js:1080:7)
termix  |     at USERAUTH_FAILURE (/app/node_modules/ssh2/lib/client.js:428:11)
termix  |     at 51 (/app/node_modules/ssh2/lib/protocol/handlers.misc.js:408:16)
termix  |     at Protocol.onPayload (/app/node_modules/ssh2/lib/protocol/Protocol.js:2059:10)
termix  |     at ChaChaPolyDecipherBinding.decrypt (/app/node_modules/ssh2/lib/protocol/crypto.js:851:26)
termix  |     at Protocol.parsePacket [as _parse] (/app/node_modules/ssh2/lib/protocol/Protocol.js:2028:25)
termix  |     at Protocol.parse (/app/node_modules/ssh2/lib/protocol/Protocol.js:313:16)
termix  |     at Socket.<anonymous> (/app/node_modules/ssh2/lib/client.js:773:21)
termix  |     at Socket.emit (node:events:509:28) {
termix  |   level: 'client-authentication'
termix  | }
termix  | [9:55:15 AM] [INFO] [🖥️] SSH connection closed [op:terminal_ssh_disconnected,user:WMkR7k4lzxxxxx,host:2,session:-gBYbhsRUiiRPvoEv9oE-]
termix  | [9:55:15 AM] [INFO] [🖥️] Terminal WebSocket disconnected [op:terminal_ws_disconnect,user:WMkR7k4lzxxxxx,session:-gBYbhsRUiiRPvoEv9oE-]
```

**Comment by seh-len** [comment]
It still isn’t working for me with the latest version of termix server. It still doesn’t prompt for the password and the connection is closed straight away.

termix server: 2.4.1
termix android 1.4.0

```
termix  | [4:32:39 AM] [INFO] [🖥️] Terminal WebSocket connection established [op:terminal_ws_connect,user:WMkR7k4lzxxxxx,session:XQFNm3Z-jetnAS9PYzbrF]
termix  | [4:32:39 AM] [INFO] [🖥️] Resolving SSH host configuration [op:terminal_host_resolve,user:WMkR7k4lzxxxxx,host:2,session:XQFNm3Z-jetnAS9PYzbrF]
termix  | [4:32:39 AM] [INFO] [🖥️] Initiating SSH connection [op:terminal_ssh_connect_attempt,user:WMkR7k4lzxxxxx,host:2,session:XQFNm3Z-jetnAS9PYzbrF]
termix  | [4:32:39 AM] [INFO] [🖥️] Host key verified successfully [op:host_key_verified,user:WMkR7k4lzxxxxx,host:2]
termix  | [4:32:39 AM] [ERROR] [🖥️] SSH connection error [op:ssh_connect,host:2]
termix  | Error: All configured authentication methods failed
termix  |     at doNextAuth (/app/node_modules/ssh2/lib/client.js:863:21)
termix  |     at tryNextAuth (/app/node_modules/ssh2/lib/client.js:1080:7)
termix  |     at USERAUTH_FAILURE (/app/node_modules/ssh2/lib/client.js:428:11)
termix  |     at 51 (/app/node_modules/ssh2/lib/protocol/handlers.misc.js:408:16)
termix  |     at Protocol.onPayload (/app/node_modules/ssh2/lib/protocol/Protocol.js:2059:10)
termix  |     at ChaChaPolyDecipherNative.decrypt (/app/node_modules/ssh2/lib/protocol/crypto.js:748:26)
termix  |     at Protocol.parsePacket [as _parse] (/app/node_modules/ssh2/lib/protocol/Protocol.js:2028:25)
termix  |     at Protocol.parse (/app/node_modules/ssh2/lib/protocol/Protocol.js:313:16)
termix  |     at Socket.<anonymous> (/app/node_modules/ssh2/lib/client.js:773:21)
termix  |     at Socket.emit (node:events:509:20) {
termix  |   level: 'client-authentication'
termix  | }
termix  | [4:32:39 AM] [INFO] [🖥️] SSH connection closed [op:terminal_ssh_disconnected,user:WMkR7k4lzxxxxx,host:2,session:XQFNm3Z-jetnAS9PYzbrF]
termix  | [4:32:39 AM] [INFO] [🖥️] Terminal WebSocket disconnected [op:terminal_ws_disconnect,user:WMkR7k4lzxxxxx,session:XQFNm3Z-jetnAS9PYzbrF]
```

I think the problem lies with the Android app, as the connection flow looks exactly the same right up until the point where the password prompt is missing.


```
termix  | [4:36:44 AM] [INFO] [🖥️] Terminal WebSocket connection established [op:terminal_ws_connect,user:WMkR7k4lzxxxxx,session:7nJqDYGZSejuvOwF1UMhe]
termix  | [4:36:44 AM] [INFO] [🖥️] Resolving SSH host configuration [op:terminal_host_resolve,user:WMkR7k4lzxxxxx,host:2,session:7nJqDYGZSejuvOwF1UMhe]
termix  | [4:36:44 AM] [INFO] [🖥️] Initiating SSH connection [op:terminal_ssh_connect_attempt,user:WMkR7k4lzxxxxx,host:2,session:7nJqDYGZSejuvOwF1UMhe]
termix  | [4:36:44 AM] [INFO] [🖥️] Host key verified successfully [op:host_key_verified,user:WMkR7k4lzxxxxx,host:2]
termix  | [4:36:44 AM] [ERROR] [🖥️] SSH connection error [op:ssh_connect,host:2]
termix  | Error: All configured authentication methods failed
termix  |     at doNextAuth (/app/node_modules/ssh2/lib/client.js:863:21)
termix  |     at tryNextAuth (/app/node_modules/ssh2/lib/client.js:1080:7)
termix  |     at USERAUTH_FAILURE (/app/node_modules/ssh2/lib/client.js:428:11)
termix  |     at 51 (/app/node_modules/ssh2/lib/protocol/handlers.misc.js:408:16)
termix  |     at Protocol.onPayload (/app/node_modules/ssh2/lib/protocol/Protocol.js:2059:10)
termix  |     at ChaChaPolyDecipherNative.decrypt (/app/node_modules/ssh2/lib/protocol/crypto.js:748:26)
termix  |     at Protocol.parsePacket [as _parse] (/app/node_modules/ssh2/lib/protocol/Protocol.js:2028:25)
termix  |     at Protocol.parse (/app/node_modules/ssh2/lib/protocol/Protocol.js:313:16)
termix  |     at Socket.<anonymous> (/app/node_modules/ssh2/lib/client.js:773:21)
termix  |     at Socket.emit (node:events:509:20) {
termix  |   level: 'client-authentication'
termix  | }
termix  | [4:36:44 AM] [INFO] [🖥️] SSH connection closed [op:terminal_ssh_disconnected,user:WMkR7k4lzxxxxx,host:2,session:7nJqDYGZSejuvOwF1UMhe]
```

**#### At this point, the web client will ask for your password. ###**

```
termix  | [4:37:47 AM] [INFO] [🖥️] Resolving SSH host configuration [op:terminal_host_resolve,user:WMkR7k4lzxxxxx,host:2,session:7nJqDYGZSejuvOwF1UMhe]
termix  | [4:37:47 AM] [INFO] [🖥️] Initiating SSH connection [op:terminal_ssh_connect_attempt,user:WMkR7k4lzxxxxx,host:2,session:7nJqDYGZSejuvOwF1UMhe]
termix  | [4:37:47 AM] [INFO] [🖥️] Host key verified successfully [op:host_key_verified,user:WMkR7k4lzxxxxx,host:2]
termix  | [4:37:47 AM] [SUCCESS] [🖥️] SSH connection established [op:terminal_ssh_connected,user:WMkR7k4lzxxxxx,host:2,session:7nJqDYGZSejuvOwF1UMhe]
termix  | [4:37:47 AM] [INFO] [🖥️] Terminal session created [op:session_created,user:WMkR7k4lzxxxxx,host:2,session:b17b0ede-fe95-4898-88f1-ee5ce0c864e0]
termix  | [4:37:47 AM] [INFO] [🖥️] Terminal session created after SSH ready [op:terminal_session_created,user:WMkR7k4lzxxxxx,host:2,session:b17b0ede-fe95-4898-88f1-ee5ce0c864e0]
termix  | [4:37:47 AM] [INFO] [🖥️] Creating shell [op:ssh_shell_start,host:2]
termix  | [4:37:47 AM] [SUCCESS] [🖥️] Terminal shell channel opened [op:terminal_shell_opened,user:WMkR7k4lzxxxxx,host:2,session:7nJqDYGZSejuvOwF1UMhe]
termix  | [4:37:47 AM] [INFO] [🖥️] WebSocket attached to session [op:session_attach,user:WMkR7k4lzxxxxx,session:b17b0ede-fe95-4898-88f1-ee5ce0c864e0]
termix  | [4:37:47 AM] [INFO] [🖥️] Session ready for persistence [op:session_ready,user:WMkR7k4lzxxxxx,host:2,session:b17b0ede-fe95-4898-88f1-ee5ce0c864e0]
```
